@extends('layouts.app', ['title' => 'Events', 'header' => 'Events'])

@section('content')
<div class="mx-auto max-w-[92rem]">
    <div class="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-sm font-medium text-moss-600">Find your scene</p><h1 class="mt-1 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Good cars. Good roads. Good company.</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-ink-700/60">Meets, shows, track evenings and drives selected for people who actually want to attend them.</p></div><form method="GET" class="flex flex-col gap-2 sm:flex-row"><select name="category" class="rounded-full border border-ink-950/10 bg-paper px-4 py-3 text-sm shadow-sm"><option value="">All event types</option>@foreach(['meet','show','track','drive','classic'] as $category)<option value="{{ $category }}" @selected(($filters['category'] ?? '') === $category)>{{ str($category)->headline() }}</option>@endforeach</select><div class="relative"><x-icon name="map-pin" class="absolute left-4 top-3.5 size-4 text-ink-700/35"/><input name="city" value="{{ $filters['city'] ?? '' }}" placeholder="City" class="rounded-full border border-ink-950/10 bg-paper py-3 pl-10 pr-4 text-sm shadow-sm"></div><button class="rounded-full bg-ink-950 px-5 py-3 text-sm font-semibold text-white">Find events</button></form></div>
    <div class="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($events as $event)<x-event-card :event="$event" />@empty<div class="col-span-full rounded-card border border-dashed border-ink-950/15 bg-paper p-12 text-center"><span class="mx-auto grid size-12 place-items-center rounded-2xl bg-canvas"><x-icon name="calendar" /></span><h2 class="mt-4 text-lg font-semibold">No events match those filters.</h2><a href="{{ route('events.index') }}" class="mt-2 inline-flex text-sm font-semibold text-moss-600">Clear filters</a></div>@endforelse</div>
    <div class="mt-8">{{ $events->links() }}</div>
</div>
@endsection
