@extends('layouts.app', ['title' => $event->title, 'header' => 'Event details'])

@section('content')
<div class="mx-auto max-w-6xl">
    <a href="{{ route('events.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-ink-700/55 hover:text-ink-950">← Explore events</a>
    <section class="relative mt-5 overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#295441] to-ink-950 p-7 text-white shadow-card sm:p-10 lg:p-12"><div class="absolute -right-12 -top-16 size-72 rounded-full border-[50px] border-white/5"></div><div class="relative max-w-3xl"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-lime-400/12 px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-lime-300">{{ $event->category }}</span>@if($event->is_featured)<span class="inline-flex items-center gap-1 text-xs font-semibold text-lime-300"><x-icon name="spark" class="size-3.5" /> Featured</span>@endif</div><h1 class="mt-6 text-balance text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">{{ $event->title }}</h1><p class="mt-5 max-w-2xl text-base leading-7 text-white/60">{{ $event->summary }}</p><div class="mt-8 flex flex-wrap gap-3 text-sm"><span class="inline-flex items-center gap-2 rounded-full bg-white/8 px-4 py-2.5"><x-icon name="calendar" class="size-4 text-lime-300" /> {{ $event->starts_at->format('D, j M · H:i') }}</span><span class="inline-flex items-center gap-2 rounded-full bg-white/8 px-4 py-2.5"><x-icon name="map-pin" class="size-4 text-lime-300" /> {{ $event->venue }}, {{ $event->city }}</span></div></div></section>
    <div class="mt-6 grid gap-5 lg:grid-cols-[1fr_22rem]">
        <div class="flex flex-col gap-5"><section class="rounded-card border border-ink-950/8 bg-paper p-6 shadow-card sm:p-8"><p class="text-xs font-semibold uppercase tracking-[0.13em] text-moss-600">The plan</p><h2 class="mt-2 text-2xl font-semibold">About this event</h2><p class="mt-5 whitespace-pre-line text-sm leading-7 text-ink-700/65">{{ $event->description }}</p><div class="mt-7 flex flex-wrap gap-2">@foreach($event->vehicle_tags ?? [] as $tag)<span class="rounded-full bg-canvas px-3 py-1.5 text-xs font-medium text-ink-700">{{ $tag }}</span>@endforeach</div></section><section class="rounded-card border border-ink-950/8 bg-paper p-6 shadow-card"><div class="grid gap-5 sm:grid-cols-3"><div><p class="text-xs text-ink-700/45">Venue</p><p class="mt-1 text-sm font-semibold">{{ $event->venue }}</p></div><div><p class="text-xs text-ink-700/45">Entry</p><p class="mt-1 text-sm font-semibold">{{ $event->price_pence ? '£'.number_format($event->price_pence / 100, 2) : 'Free' }}</p></div><div><p class="text-xs text-ink-700/45">Community</p><p class="mt-1 text-sm font-semibold">{{ $event->attendees_count }} interested</p></div></div></section></div>
        <aside class="h-fit rounded-card border border-ink-950/8 bg-paper p-6 shadow-card lg:sticky lg:top-24"><div class="flex items-center justify-between"><p class="text-sm font-semibold">Your attendance</p><span class="grid size-10 place-items-center rounded-xl bg-lime-400 text-ink-950"><x-icon name="ticket" class="size-4.5" /></span></div>@if($attendance)<div class="mt-5 rounded-2xl bg-moss-100 p-4 text-moss-700"><p class="text-sm font-semibold">{{ str($attendance->pivot->status)->headline() }}</p><p class="mt-1 text-xs">We will keep event updates together here.</p></div><form method="POST" action="{{ route('events.attendance.destroy', $event) }}" class="mt-4">@csrf @method('DELETE')<button class="w-full rounded-full border border-ink-950/10 px-4 py-2.5 text-sm font-semibold text-ink-700">Remove from my events</button></form>@else<form method="POST" action="{{ route('events.attendance.store', $event) }}" class="mt-5 flex flex-col gap-4">@csrf<label class="flex flex-col gap-2 text-sm font-medium">I’m<select name="status" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3 text-sm"><option value="going">Going</option><option value="interested">Interested</option></select></label>@if($vehicles->isNotEmpty())<label class="flex flex-col gap-2 text-sm font-medium">Bring a vehicle <span class="font-normal text-ink-700/40">Optional</span><select name="vehicle_id" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3 text-sm"><option value="">Decide later</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}">{{ $vehicle->make }} {{ $vehicle->model }}</option>@endforeach</select></label>@endif<button class="rounded-full bg-ink-950 px-5 py-3 text-sm font-semibold text-white">Add to my events</button></form>@endif<div class="mt-5 border-t border-ink-950/8 pt-5"><p class="text-xs leading-5 text-ink-700/50"><x-icon name="shield" class="mr-1 inline size-3.5 text-moss-600" /> Your vehicle selection is visible only to the organiser.</p></div></aside>
    </div>
</div>
@endsection
