@extends('layouts.app', ['title' => 'Administration', 'header' => 'Administration'])

@section('content')
<div class="mx-auto max-w-[92rem]">
    <div><p class="text-sm font-medium text-moss-600">Operations</p><h1 class="mt-1 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Product health and activity.</h1></div>
    <div class="mt-5 flex flex-wrap gap-2"><a href="{{ route('admin.bookings.index') }}" class="rounded-full bg-ink-950 px-4 py-2.5 text-xs font-semibold text-white">Manage bookings</a><a href="{{ route('admin.events.index') }}" class="rounded-full border border-ink-950/10 bg-paper px-4 py-2.5 text-xs font-semibold">Manage events</a><a href="{{ route('admin.specialists.index') }}" class="rounded-full border border-ink-950/10 bg-paper px-4 py-2.5 text-xs font-semibold">Manage specialists</a></div>
    <div class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Members', $stats['members'], 'users'], ['Vehicles', $stats['vehicles'], 'car'], ['Bookings', $stats['bookings'], 'ticket'], ['Events', $stats['events'], 'calendar']] as [$label, $value, $icon])<div class="rounded-card border border-ink-950/8 bg-paper p-5 shadow-card"><div class="flex items-center justify-between"><span class="grid size-10 place-items-center rounded-xl bg-canvas text-moss-600"><x-icon :name="$icon" class="size-4.5" /></span><span class="text-xs text-ink-700/40">All time</span></div><p class="mt-6 text-3xl font-semibold tracking-tight">{{ number_format($value) }}</p><p class="mt-1 text-sm text-ink-700/50">{{ $label }}</p></div>@endforeach</div>
    <div class="mt-6 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><section class="rounded-card border border-ink-950/8 bg-paper p-5 shadow-card sm:p-6"><div><p class="text-xs font-semibold uppercase tracking-[0.13em] text-moss-600">Service marketplace</p><h2 class="mt-1 text-xl font-semibold">Pending booking requests</h2></div><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[620px] text-left"><thead><tr class="border-b border-ink-950/8 text-[0.65rem] uppercase tracking-wider text-ink-700/40"><th class="pb-3 font-semibold">Member</th><th class="pb-3 font-semibold">Vehicle</th><th class="pb-3 font-semibold">Specialist</th><th class="pb-3 font-semibold">Requested</th></tr></thead><tbody class="divide-y divide-ink-950/8">@forelse($pendingBookings as $booking)<tr class="text-sm"><td class="py-4"><p class="font-semibold">{{ $booking->user->name }}</p><p class="text-xs text-ink-700/40">{{ $booking->user->email }}</p></td><td class="py-4">{{ $booking->vehicle->make }} {{ $booking->vehicle->model }}</td><td class="py-4">{{ $booking->specialist->name }}</td><td class="py-4 text-ink-700/55">{{ $booking->created_at->diffForHumans() }}</td></tr>@empty<tr><td colspan="4" class="py-10 text-center text-sm text-ink-700/45">No pending requests.</td></tr>@endforelse</tbody></table></div></section><aside class="flex flex-col gap-5"><section class="rounded-card border border-ink-950/8 bg-paper p-5 shadow-card sm:p-6"><p class="text-xs font-semibold uppercase tracking-[0.13em] text-moss-600">New members</p><div class="mt-4 flex flex-col divide-y divide-ink-950/8">@foreach($recentUsers as $user)<div class="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><span class="grid size-9 place-items-center rounded-full bg-canvas text-xs font-semibold">{{ str($user->name)->substr(0, 1) }}</span><div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold">{{ $user->name }}</p><p class="truncate text-xs text-ink-700/40">{{ $user->email }}</p></div><span class="text-[0.65rem] text-ink-700/35">{{ $user->created_at->diffForHumans(short: true) }}</span></div>@endforeach</div></section><section class="rounded-card bg-ink-950 p-6 text-white shadow-card"><p class="text-xs font-semibold uppercase tracking-[0.13em] text-lime-300">Content coverage</p><div class="mt-5 grid grid-cols-3 gap-2 text-center"><div class="rounded-xl bg-white/7 p-3"><p class="text-xl font-semibold">{{ $contentCounts['posts'] }}</p><p class="mt-1 text-[0.6rem] text-white/40">Posts</p></div><div class="rounded-xl bg-white/7 p-3"><p class="text-xl font-semibold">{{ $contentCounts['published_events'] }}</p><p class="mt-1 text-[0.6rem] text-white/40">Events</p></div><div class="rounded-xl bg-white/7 p-3"><p class="text-xl font-semibold">{{ $contentCounts['verified_specialists'] }}</p><p class="mt-1 text-[0.6rem] text-white/40">Partners</p></div></div></section></aside></div>
</div>
@endsection
