@extends('layouts.app', ['title' => 'Add a vehicle', 'header' => 'Add a vehicle'])

@section('content')
<div class="mx-auto max-w-3xl">
    <a href="{{ route('vehicles.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-ink-700/60 hover:text-ink-950">← Back to garage</a>
    <div class="mt-6 overflow-hidden rounded-[2rem] border border-ink-950/8 bg-paper shadow-card">
        <div class="relative overflow-hidden bg-ink-950 p-7 text-white sm:p-10"><div class="absolute right-0 top-0 size-64 rounded-full bg-lime-400/10 blur-3xl"></div><div class="relative max-w-xl"><span class="inline-flex rounded-full bg-white/8 px-3 py-1.5 text-xs font-semibold text-lime-300">Registration lookup</span><h1 class="mt-5 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Add the car outside.</h1><p class="mt-3 text-sm leading-6 text-white/55">We will prepare a working vehicle record, MOT timeline and the first set of reminders. Live DVLA/DVSA credentials can replace the development provider without changing this flow.</p></div></div>
        <form method="POST" action="{{ route('vehicles.store') }}" class="grid gap-6 p-7 sm:grid-cols-2 sm:p-10">
            @csrf
            <label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Registration number<div class="flex max-w-sm items-center rounded-xl border-2 border-ink-950 bg-[#f2d749] p-1.5 shadow-sm"><span class="grid h-11 w-8 place-items-center rounded-lg bg-[#194b9b] text-[0.55rem] font-bold text-white">UK</span><input name="registration" value="{{ old('registration') }}" required maxlength="16" placeholder="AB12 CDE" class="min-w-0 flex-1 bg-transparent px-4 py-2 text-center font-mono text-xl font-bold uppercase tracking-[0.12em] outline-none placeholder:text-ink-950/25"></div><span class="text-xs font-normal text-ink-700/50">Spaces are optional.</span></label>
            <label class="flex flex-col gap-2 text-sm font-medium">Current mileage <span class="font-normal text-ink-700/45">Optional</span><div class="relative"><input name="current_mileage" type="number" min="0" value="{{ old('current_mileage') }}" placeholder="38,420" class="w-full rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5 pr-12 text-sm outline-none focus:border-moss-600 focus:ring-4 focus:ring-moss-100"><span class="absolute right-4 top-3.5 text-sm text-ink-700/45">mi</span></div></label>
            <label class="flex flex-col gap-2 text-sm font-medium">Insurance renewal <span class="font-normal text-ink-700/45">Optional</span><input name="insurance_due_at" type="date" value="{{ old('insurance_due_at') }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5 text-sm outline-none focus:border-moss-600 focus:ring-4 focus:ring-moss-100"></label>
            <label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Garage visibility<select name="visibility" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5 text-sm outline-none focus:border-moss-600 focus:ring-4 focus:ring-moss-100"><option value="private">Private — only me</option><option value="shared">Shared — invited drivers</option><option value="public">Public — enthusiast profile</option></select></label>
            <div class="flex flex-col-reverse gap-3 border-t border-ink-950/8 pt-6 sm:col-span-2 sm:flex-row sm:items-center sm:justify-between"><p class="text-xs leading-5 text-ink-700/50"><x-icon name="shield" class="mr-1 inline size-3.5 text-moss-600" /> Private by default. You control every share.</p><button class="inline-flex items-center justify-center gap-2 rounded-full bg-ink-950 px-6 py-3.5 text-sm font-semibold text-white">Build my vehicle record <x-icon name="arrow-right" class="size-4" /></button></div>
        </form>
    </div>
</div>
@endsection
