Listen ${PORT}
ServerName localhost
ServerTokens Prod
ServerSignature Off
<VirtualHost *:${PORT}>
    DocumentRoot /app/public
    <Directory /app/public>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
<IfModule mpm_prefork_module>
    StartServers 2
    MinSpareServers 2
    MaxSpareServers 3
    MaxRequestWorkers 5
    MaxConnectionsPerChild 500
</IfModule>
