@extends('layouts.app', ['title' => 'Settings', 'header' => 'Settings'])

@section('content')
@php $preferences = $user->preferences ?? []; @endphp
<div class="mx-auto max-w-4xl">
    <div><p class="text-sm font-medium text-moss-600">Your account</p><h1 class="mt-1 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Profile and preferences.</h1><p class="mt-3 text-sm leading-6 text-ink-700/60">Shape the experience around the way you own and enjoy cars.</p></div>
    <form method="POST" action="{{ route('profile.update') }}" class="mt-8 overflow-hidden rounded-[2rem] border border-ink-950/8 bg-paper shadow-card">@csrf @method('PATCH')<div class="grid gap-6 p-6 sm:grid-cols-2 sm:p-8"><label class="flex flex-col gap-2 text-sm font-medium">Name<input name="name" value="{{ old('name', $user->name) }}" required class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5 text-sm"></label><label class="flex flex-col gap-2 text-sm font-medium">Username<input name="username" value="{{ old('username', $user->username) }}" required class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5 text-sm"></label><label class="flex flex-col gap-2 text-sm font-medium">Postcode<input name="postcode" value="{{ old('postcode', $user->postcode) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5 text-sm"></label><label class="flex flex-col gap-2 text-sm font-medium">Primary goal<select name="primary_goal" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5 text-sm">@foreach(['maintain' => 'Keep on top of maintenance', 'project' => 'Track a project or build', 'events' => 'Find events and community', 'multi_vehicle' => 'Manage multiple vehicles'] as $value => $label)<option value="{{ $value }}" @selected(($preferences['primary_goal'] ?? 'maintain') === $value)>{{ $label }}</option>@endforeach</select></label><label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Bio <span class="font-normal text-ink-700/40">Shown on public vehicle profiles</span><textarea name="bio" rows="4" class="resize-none rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5 text-sm">{{ old('bio', $user->bio) }}</textarea></label><label class="flex items-start gap-3 rounded-2xl bg-canvas p-4 sm:col-span-2"><input type="checkbox" name="email_reminders" value="1" @checked($preferences['email_reminders'] ?? true) class="mt-1 size-4 rounded border-ink-950/20 text-moss-600"><span><span class="block text-sm font-semibold">Email reminders</span><span class="mt-1 block text-xs leading-5 text-ink-700/50">Send an email when an important vehicle date enters its reminder window.</span></span></label></div><div class="flex justify-end border-t border-ink-950/8 px-6 py-5 sm:px-8"><button class="rounded-full bg-ink-950 px-6 py-3 text-sm font-semibold text-white">Save preferences</button></div></form>
    <section class="mt-5 rounded-card border border-ink-950/8 bg-paper p-6 shadow-card"><div class="flex items-start gap-4"><span class="grid size-11 shrink-0 place-items-center rounded-2xl bg-moss-100 text-moss-700"><x-icon name="shield" /></span><div><h2 class="text-lg font-semibold">Data belongs to you.</h2><p class="mt-2 text-sm leading-6 text-ink-700/60">Vehicle profiles remain private unless you publish them. Private documents are never included in community posts or public passports.</p></div></div></section>
</div>
@endsection
