@extends('layouts.app', ['title' => 'Bookings', 'header' => 'Bookings'])

@section('content')
<div class="mx-auto max-w-6xl">
    <div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-medium text-moss-600">Work requests</p><h1 class="mt-1 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">From request to verified record.</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-ink-700/60">Track quotes and appointments. Completed work can flow back into the relevant vehicle history.</p></div><a href="{{ route('specialists.index') }}" class="inline-flex items-center justify-center gap-2 rounded-full bg-ink-950 px-5 py-3 text-sm font-semibold text-white"><x-icon name="search" class="size-4" /> Find a specialist</a></div>
    <div class="mt-8 flex flex-col gap-4">@forelse($bookings as $booking)<article class="rounded-card border border-ink-950/8 bg-paper p-5 shadow-card sm:p-6"><div class="grid gap-5 md:grid-cols-[auto_1fr_auto] md:items-center"><span class="grid size-12 place-items-center rounded-2xl {{ in_array($booking->status, ['confirmed','completed']) ? 'bg-moss-100 text-moss-700' : 'bg-amber-100 text-amber-700' }}"><x-icon name="wrench" /></span><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h2 class="text-base font-semibold">{{ $booking->service }}</h2><span class="rounded-full bg-canvas px-2.5 py-1 text-[0.63rem] font-semibold text-ink-700">{{ str($booking->status)->headline() }}</span></div><p class="mt-1 text-sm text-ink-700/55">{{ $booking->specialist->name }} · {{ $booking->vehicle->make }} {{ $booking->vehicle->model }}</p><p class="mt-2 text-xs text-ink-700/40">Requested for {{ $booking->requested_start_at->format('D, j M Y · H:i') }} · Ref {{ str($booking->confirmation_code)->substr(0, 8)->upper() }}</p></div><div class="flex items-center gap-3 md:justify-end">@if($booking->quote_pence)<div class="text-right"><p class="text-xs text-ink-700/40">Quote</p><p class="text-lg font-semibold">£{{ number_format($booking->quote_pence / 100, 2) }}</p></div>@endif @if($booking->status === 'requested')<form method="POST" action="{{ route('bookings.destroy', $booking) }}">@csrf @method('DELETE')<button class="rounded-full border border-ink-950/10 px-3 py-2 text-xs font-semibold text-ink-700">Cancel</button></form>@endif</div></div>@if($booking->description)<p class="mt-5 border-t border-ink-950/8 pt-4 text-sm leading-6 text-ink-700/55">{{ $booking->description }}</p>@endif</article>@empty<div class="rounded-[2rem] border border-dashed border-ink-950/15 bg-paper p-12 text-center"><span class="mx-auto grid size-12 place-items-center rounded-2xl bg-canvas"><x-icon name="wrench" /></span><h2 class="mt-4 text-lg font-semibold">No work requested yet.</h2><p class="mt-2 text-sm text-ink-700/50">Find the right specialist when your plan needs one.</p></div>@endforelse</div>
    <div class="mt-8">{{ $bookings->links() }}</div>
</div>
@endsection
