@extends('layouts.app', ['title' => $specialist->name, 'header' => 'Specialist profile'])

@section('content')
<div class="mx-auto max-w-6xl">
    <a href="{{ route('specialists.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-ink-700/55 hover:text-ink-950">← Find specialists</a>
    <section class="mt-5 overflow-hidden rounded-[2rem] border border-ink-950/8 bg-paper shadow-card"><div class="relative bg-ink-950 p-7 text-white sm:p-10"><div class="absolute right-0 top-0 size-64 rounded-full bg-lime-400/10 blur-3xl"></div><div class="relative flex flex-col gap-7 sm:flex-row sm:items-start sm:justify-between"><div class="max-w-3xl"><div class="flex flex-wrap items-center gap-2">@if($specialist->is_verified)<span class="inline-flex items-center gap-1 rounded-full bg-lime-400/12 px-3 py-1.5 text-xs font-semibold text-lime-300"><x-icon name="shield" class="size-3.5" /> Verified specialist</span>@endif<span class="text-xs text-white/45">{{ $specialist->price_level }}</span></div><h1 class="mt-5 text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">{{ $specialist->name }}</h1><p class="mt-4 max-w-2xl text-base leading-7 text-white/55">{{ $specialist->tagline }}</p></div><div class="shrink-0 rounded-2xl bg-white/8 px-5 py-4 text-center"><p class="text-3xl font-semibold text-lime-400">{{ $specialist->rating }}</p><p class="mt-1 text-xs text-white/45">{{ number_format($specialist->review_count) }} reviews</p></div></div></div><div class="grid gap-4 p-6 sm:grid-cols-3 sm:p-8"><div><p class="text-xs text-ink-700/45">Location</p><p class="mt-1 text-sm font-semibold">{{ $specialist->city }}, {{ $specialist->postcode }}</p></div><div><p class="text-xs text-ink-700/45">Telephone</p><p class="mt-1 text-sm font-semibold">{{ $specialist->phone }}</p></div><div><p class="text-xs text-ink-700/45">Typical hours</p><p class="mt-1 text-sm font-semibold">{{ $specialist->opening_hours['weekdays'] ?? 'Contact for hours' }}</p></div></div></section>
    <div class="mt-6 grid gap-5 lg:grid-cols-[1fr_23rem]">
        <div class="flex flex-col gap-5"><section class="rounded-card border border-ink-950/8 bg-paper p-6 shadow-card sm:p-8"><p class="text-xs font-semibold uppercase tracking-[0.13em] text-moss-600">About</p><h2 class="mt-2 text-2xl font-semibold">Why owners choose them</h2><p class="mt-5 whitespace-pre-line text-sm leading-7 text-ink-700/65">{{ $specialist->description }}</p><div class="mt-7 flex flex-wrap gap-2">@foreach($specialist->categories as $category)<span class="rounded-full bg-canvas px-3 py-1.5 text-xs font-medium text-ink-700">{{ str($category)->headline() }}</span>@endforeach</div></section><section class="rounded-card border border-ink-950/8 bg-paper p-6 shadow-card"><div class="flex items-start gap-4"><span class="grid size-11 shrink-0 place-items-center rounded-2xl bg-moss-100 text-moss-700"><x-icon name="shield" /></span><div><h2 class="text-lg font-semibold">Verified completion records</h2><p class="mt-2 text-sm leading-6 text-ink-700/60">Completed work can be written back to your vehicle passport with the provider, mileage, cost and supporting invoice linked together.</p></div></div></section></div>
        <aside class="h-fit rounded-card border border-ink-950/8 bg-paper p-6 shadow-card lg:sticky lg:top-24"><p class="text-xs font-semibold uppercase tracking-[0.13em] text-moss-600">Request work</p><h2 class="mt-1 text-xl font-semibold">Start with the details.</h2>@if($vehicles->isEmpty())<div class="mt-5 rounded-2xl bg-amber-100 p-4 text-sm text-amber-700"><p class="font-semibold">Add a vehicle first.</p><p class="mt-1 text-xs leading-5">A booking stays attached to the right vehicle and its history.</p><a href="{{ route('vehicles.create') }}" class="mt-3 inline-flex font-semibold">Add vehicle →</a></div>@else<form method="POST" action="{{ route('bookings.store') }}" class="mt-5 flex flex-col gap-4">@csrf<input type="hidden" name="specialist_id" value="{{ $specialist->id }}"><label class="flex flex-col gap-2 text-sm font-medium">Vehicle<select name="vehicle_id" required class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3 text-sm">@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}">{{ $vehicle->make }} {{ $vehicle->model }} · {{ $vehicle->registration }}</option>@endforeach</select></label><label class="flex flex-col gap-2 text-sm font-medium">Service needed<input name="service" required placeholder="e.g. Annual service" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3 text-sm"></label><label class="flex flex-col gap-2 text-sm font-medium">Preferred date<input name="requested_start_at" type="datetime-local" min="{{ now()->addHour()->format('Y-m-d\TH:i') }}" required class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3 text-sm"></label><label class="flex flex-col gap-2 text-sm font-medium">What should they know? <span class="font-normal text-ink-700/40">Optional</span><textarea name="description" rows="3" class="resize-none rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3 text-sm"></textarea></label><button class="rounded-full bg-ink-950 px-5 py-3 text-sm font-semibold text-white">Send booking request</button></form>@endif<p class="mt-5 border-t border-ink-950/8 pt-5 text-xs leading-5 text-ink-700/45">This sends a request. No payment is taken until a quote is accepted.</p></aside>
    </div>
</div>
@endsection
