@php($editing = $specialist->exists)
<form method="POST" action="{{ $editing ? route('admin.specialists.update', $specialist) : route('admin.specialists.store') }}" class="grid gap-5 sm:grid-cols-2">@csrf @if($editing) @method('PUT') @endif
<label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Name<input name="name" required value="{{ old('name', $specialist->name) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
<label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Tagline<input name="tagline" required maxlength="180" value="{{ old('tagline', $specialist->tagline) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
<label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Description<textarea name="description" required rows="6" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5">{{ old('description', $specialist->description) }}</textarea></label>
<label class="flex flex-col gap-2 text-sm font-medium">Categories <span class="text-xs font-normal text-ink-700/45">Comma separated</span><input name="categories" required value="{{ old('categories', implode(', ', $specialist->categories ?? [])) }}" placeholder="servicing, tyres, classic" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
<label class="flex flex-col gap-2 text-sm font-medium">Brands <span class="text-xs font-normal text-ink-700/45">Comma separated</span><input name="brands" value="{{ old('brands', implode(', ', $specialist->brands ?? [])) }}" placeholder="Audi, BMW, Porsche" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
<label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Address<input name="address" required value="{{ old('address', $specialist->address) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
<label class="flex flex-col gap-2 text-sm font-medium">City<input name="city" required value="{{ old('city', $specialist->city) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
<label class="flex flex-col gap-2 text-sm font-medium">Postcode<input name="postcode" required value="{{ old('postcode', $specialist->postcode) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
<label class="flex flex-col gap-2 text-sm font-medium">Price level<select name="price_level" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5">@foreach(['£','££','£££'] as $level)<option value="{{ $level }}" @selected(old('price_level', $specialist->price_level ?: '££') === $level)>{{ $level }}</option>@endforeach</select></label>
<label class="flex flex-col gap-2 text-sm font-medium">Phone<input name="phone" value="{{ old('phone', $specialist->phone) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
<label class="flex flex-col gap-2 text-sm font-medium">Email<input name="email" type="email" value="{{ old('email', $specialist->email) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
<label class="flex flex-col gap-2 text-sm font-medium">Website URL<input name="website_url" type="url" value="{{ old('website_url', $specialist->website_url) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
<label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Image URL<input name="image_url" type="url" value="{{ old('image_url', $specialist->image_url) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
<div class="flex gap-5 sm:col-span-2"><label class="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="is_verified" value="1" @checked(old('is_verified', $specialist->is_verified))> Verified</label><label class="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $specialist->is_featured))> Featured</label></div>
<div class="flex justify-end gap-3 border-t border-ink-950/8 pt-5 sm:col-span-2"><a href="{{ route('admin.specialists.index') }}" class="rounded-full border border-ink-950/10 px-5 py-3 text-sm font-semibold">Cancel</a><button class="rounded-full bg-ink-950 px-5 py-3 text-sm font-semibold text-white">{{ $editing ? 'Save changes' : 'Add specialist' }}</button></div></form>
