@php($editing = $event->exists)
<form method="POST" action="{{ $editing ? route('admin.events.update', $event) : route('admin.events.store') }}" class="grid gap-5 sm:grid-cols-2">
    @csrf
    @if($editing) @method('PUT') @endif
    <label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Title<input name="title" required maxlength="255" value="{{ old('title', $event->title) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5 outline-none focus:border-moss-600"></label>
    <label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Summary<textarea name="summary" required maxlength="320" rows="2" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5 outline-none focus:border-moss-600">{{ old('summary', $event->summary) }}</textarea></label>
    <label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Description<textarea name="description" required rows="7" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5 outline-none focus:border-moss-600">{{ old('description', $event->description) }}</textarea></label>
    <label class="flex flex-col gap-2 text-sm font-medium">Category<select name="category" required class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5">@foreach(['meet','show','track','drive','classic'] as $category)<option value="{{ $category }}" @selected(old('category', $event->category) === $category)>{{ ucfirst($category) }}</option>@endforeach</select></label>
    <label class="flex flex-col gap-2 text-sm font-medium">Venue<input name="venue" required value="{{ old('venue', $event->venue) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
    <label class="flex flex-col gap-2 text-sm font-medium">City<input name="city" required value="{{ old('city', $event->city) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
    <label class="flex flex-col gap-2 text-sm font-medium">Postcode<input name="postcode" value="{{ old('postcode', $event->postcode) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
    <label class="flex flex-col gap-2 text-sm font-medium">Starts at<input name="starts_at" type="datetime-local" required value="{{ old('starts_at', $event->starts_at?->format('Y-m-d\\TH:i')) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
    <label class="flex flex-col gap-2 text-sm font-medium">Ends at<input name="ends_at" type="datetime-local" value="{{ old('ends_at', $event->ends_at?->format('Y-m-d\\TH:i')) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
    <label class="flex flex-col gap-2 text-sm font-medium">Capacity<input name="capacity" type="number" min="1" value="{{ old('capacity', $event->capacity) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
    <label class="flex flex-col gap-2 text-sm font-medium">Price (£)<input name="price_pounds" type="number" min="0" step="0.01" value="{{ old('price_pounds', $event->exists ? number_format($event->price_pence / 100, 2, '.', '') : '0.00') }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
    <label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Vehicle tags <span class="text-xs font-normal text-ink-700/45">Comma separated</span><input name="vehicle_tags" value="{{ old('vehicle_tags', implode(', ', $event->vehicle_tags ?? [])) }}" placeholder="Classic, German, All cars" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
    <label class="flex flex-col gap-2 text-sm font-medium sm:col-span-2">Cover image URL<input name="cover_image_url" type="url" value="{{ old('cover_image_url', $event->cover_image_url) }}" class="rounded-2xl border border-ink-950/12 bg-canvas px-4 py-3.5"></label>
    <div class="flex flex-wrap gap-5 sm:col-span-2"><label class="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $event->is_published))> Published</label><label class="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $event->is_featured))> Featured</label></div>
    <div class="flex justify-end gap-3 border-t border-ink-950/8 pt-5 sm:col-span-2"><a href="{{ route('admin.events.index') }}" class="rounded-full border border-ink-950/10 px-5 py-3 text-sm font-semibold">Cancel</a><button class="rounded-full bg-ink-950 px-5 py-3 text-sm font-semibold text-white">{{ $editing ? 'Save changes' : 'Create event' }}</button></div>
</form>
