@extends('layouts.app', ['title' => 'Community', 'header' => 'Community'])

@section('content')
<div class="mx-auto max-w-6xl">
    <div><p class="text-sm font-medium text-moss-600">From the garage</p><h1 class="mt-1 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Real cars. Useful stories.</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-ink-700/60">Build updates, good roads and lessons worth passing to the next owner.</p></div>
    <div class="mt-8 grid gap-5 lg:grid-cols-[1fr_20rem]">
        <div class="flex flex-col gap-5">
            <section class="rounded-card border border-ink-950/8 bg-paper p-5 shadow-card"><form method="POST" action="{{ route('posts.store') }}">@csrf<div class="flex gap-3"><span class="grid size-10 shrink-0 place-items-center rounded-full bg-ink-950 text-sm font-semibold text-lime-400">{{ str(auth()->user()->name)->substr(0, 1)->upper() }}</span><textarea name="body" rows="3" required placeholder="Share an update, a useful lesson or the road you found…" class="min-h-24 flex-1 resize-none rounded-2xl border border-ink-950/10 bg-canvas px-4 py-3 text-sm outline-none focus:border-moss-600"></textarea></div><div class="mt-4 flex flex-col gap-3 border-t border-ink-950/8 pt-4 sm:flex-row sm:items-center sm:justify-between"><div class="flex flex-wrap gap-2"><select name="category" class="rounded-full border border-ink-950/10 bg-canvas px-3 py-2 text-xs font-medium"><option value="update">Update</option><option value="build">Build</option><option value="question">Question</option><option value="drive">Drive</option></select><select name="vehicle_id" class="max-w-48 rounded-full border border-ink-950/10 bg-canvas px-3 py-2 text-xs font-medium"><option value="">No vehicle</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}">{{ $vehicle->make }} {{ $vehicle->model }}</option>@endforeach</select><input type="hidden" name="visibility" value="public"></div><button class="rounded-full bg-ink-950 px-5 py-2.5 text-xs font-semibold text-white">Share update</button></div></form></section>
            @forelse($posts as $post)
                <article class="rounded-card border border-ink-950/8 bg-paper p-5 shadow-card sm:p-6">
                    <div class="flex items-start gap-3"><span class="grid size-10 shrink-0 place-items-center rounded-full bg-sand-100 text-sm font-semibold text-ink-800">{{ str($post->user->name)->substr(0, 1)->upper() }}</span><div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-semibold">{{ $post->user->name }}</p><p class="mt-0.5 text-xs text-ink-700/45">{{ '@'.$post->user->username }} · {{ $post->published_at->diffForHumans() }}</p></div>@if($post->user_id === auth()->id())<form method="POST" action="{{ route('posts.destroy', $post) }}">@csrf @method('DELETE')<button class="text-ink-700/30 hover:text-rose-700" aria-label="Delete post"><x-icon name="x" class="size-4" /></button></form>@endif</div>@if($post->vehicle)<div class="mt-3 inline-flex items-center gap-2 rounded-full bg-canvas px-3 py-1.5 text-xs font-medium text-ink-700"><x-icon name="car" class="size-3.5 text-moss-600" /> {{ $post->vehicle->year }} {{ $post->vehicle->make }} {{ $post->vehicle->model }}</div>@endif<p class="mt-4 whitespace-pre-line text-[0.94rem] leading-7 text-ink-800">{{ $post->body }}</p><div class="mt-5 flex items-center justify-between border-t border-ink-950/8 pt-4"><span class="rounded-full bg-moss-100 px-2.5 py-1 text-[0.63rem] font-semibold text-moss-700">{{ str($post->category)->headline() }}</span><span class="text-xs font-medium text-ink-700/45">♥ {{ $post->likes_count }}</span></div></div></div>
                </article>
            @empty
                <div class="rounded-card border border-dashed border-ink-950/15 bg-paper p-12 text-center"><p class="text-sm font-semibold">The community is quiet.</p><p class="mt-1 text-xs text-ink-700/50">Start with something useful from your garage.</p></div>
            @endforelse
            <div>{{ $posts->links() }}</div>
        </div>
        <aside class="hidden flex-col gap-5 lg:flex"><div class="rounded-card bg-ink-950 p-5 text-white shadow-card"><span class="grid size-10 place-items-center rounded-2xl bg-lime-400 text-ink-950"><x-icon name="spark" class="size-4.5" /></span><h2 class="mt-5 text-lg font-semibold">Good community starts with useful detail.</h2><p class="mt-2 text-sm leading-6 text-white/50">Share the part number, the route, the cost or the lesson — the things another owner can use.</p></div><div class="rounded-card border border-ink-950/8 bg-paper p-5 shadow-card"><p class="text-xs font-semibold uppercase tracking-[0.13em] text-moss-600">Community principles</p><ul class="mt-4 flex flex-col gap-3 text-sm text-ink-700/65"><li class="flex gap-2"><x-icon name="check" class="mt-0.5 size-4 text-moss-600" /> Respect every kind of car</li><li class="flex gap-2"><x-icon name="check" class="mt-0.5 size-4 text-moss-600" /> Be precise and honest</li><li class="flex gap-2"><x-icon name="check" class="mt-0.5 size-4 text-moss-600" /> Keep road safety first</li></ul></div></aside>
    </div>
</div>
@endsection
